### ISSUE TITLE
Add Test Plan Item validation to the BOT

### ISSUE THREAD

**Issue by sandy081** [JacksonKearl/vscode-triage-github-actions#4]
**Problem**: Team creates Test plan items with label `testplan-item` for testing their features during the endgame. We have a tool that parse all these test plan items and generate assignments  by taking care of load balance.

Format of the test plan items is documented here - https://github.com/microsoft/vscode/wiki/Writing-Test-Plan-Items. And the tool respects this  while parsing and skips those which do not adhere to this syntax. It also happens sometimes test plan items gets unassigned. This causes the features getting skipped in testing.

**Idea**: Add following capability to the BOT

- BOT validates the issue labelled with `testplan-item`.
- If all is good no action needed.
- If test plan items are not written well
  - Remove label `testplan-item`
  - Add label `testplan-item-invalid`
  - Add comment that test plan item is not as per expected and include the link to the wiki. Ask the author to fix it and update the label to `testplan-item`.
  - BOT kicks in again and validates
  - If all is good then removes the label `testplan-item-invalid`. Otherwise goes to step 1.

**Comment by sandy081** [comment]
Here is the code to validate TPI - https://github.com/microsoft/vscode-tools/blob/0e304ab4599ebcd7ac2b989e989392a7cae75296/src/server/endgame/tpiParser.ts#L27

**Comment by JacksonKearl** [comment]
Added in d0cfffa42f1e13abd047d426b1da7353d80854ed
